services:
    flowise:
        image: flowise:latest
        restart: always
        environment:
            - PORT=${PORT}
            # LOGGING
            - DEBUG=${DEBUG}
            # SETTINGS
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
           # Default Teradata Configuration env to refer into flowise
            - TD_MCP_SERVER=http://teradata-mcp-server:8001/mcp
        ports:
            - "${PORT}:${PORT}"
        extra_hosts:
            - "dbccop1:${DATABASE_HOST}"
        container_name: flowise
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/api/v1/ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - ${DATA_DIR}/.flowise:/root/.flowise
    teradata-mcp-server:
        image: teradata-mcp-server:latest
        restart: always
        environment:
            - DATABASE_URI=${DATABASE_URI}
            - LOGMECH=${LOGMECH}
            - MCP_TRANSPORT=${MCP_TRANSPORT}
            - MCP_PATH=${MCP_PATH}
            - MCP_HOST=${MCP_HOST}
            - MCP_PORT=${MCP_PORT}
            - PROFILE=${PROFILE}
            - TD_BASE_URL=${TD_BASE_URL}
            - TD_PAT=${TD_PAT}
            - TD_PEM=${TD_PEM}
            - VS_NAME=${VS_NAME}
        container_name: teradata-mcp-server
        extra_hosts:
            - "dbccop1:${DATABASE_HOST}"
        ports:
            - "${MCP_PORT}:${MCP_PORT}"
        volumes:
            - ${TD_PEM}:${TD_PEM}
        tty: true
networks:
  default:
    name: td-ai-stack
    external: false