services:
    flowise:
        image: flowiseai/flowise:latest
        restart: always
        environment:
            - PORT=${PORT}
            # LOGGING
            - DEBUG=${DEBUG}
            # SETTINGS
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
           # Default Teradata Configuration env to refer into flowise
            - TD_MCP_SERVER=http://teradata-mcp-server:8001/mcp
        ports:
            - '${PORT}:${PORT}'
        container_name: flowise
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/api/v1/ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - ${DATA_DIR:-./.flowise}:/root/.flowise
    teradata-mcp-server:
        build:
            context: ../..
            dockerfile: Dockerfile
            args:
                ENABLE_FS_MODULE: "true"
                ENABLE_EVS_MODULE: "true"
        image: teradata-mcp-server:latest
        restart: always
        environment:
            - DATABASE_URI=${DATABASE_URI}
            - LOGMECH=${LOGMECH}
            - MCP_TRANSPORT=${MCP_TRANSPORT}
            - MCP_PATH=${MCP_PATH}
            - MCP_HOST=${MCP_HOST}
            - MCP_PORT=${MCP_PORT}
            - PROFILE=${PROFILE}
        container_name: teradata-mcp-server
        ports:
            - "${MCP_PORT}:${MCP_PORT}"
        tty: true
networks:
  default:
    name: td-ai-stack
    external: false
