[project]
name = "teradata-mcp"
version = "0.1.0"
description = "Teradata MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.36",
    "mcp[cli]>=1.6.0",
    "pip>=25.0.1",
    "pydantic>=2.11.3",
    "pydantic-ai>=0.1.2",
    "teradatasql>=20.0.0.28",
]

[[project.authors]]
name = "Teradata"
email = "daniel.tehan@teradata.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
teradata-mcp = "teradata_mcp:main"
