all:
  tool:
    - .*
  prompt:
    - ^(?!test_).*
  resource:
    - .*

tester:
  tool:
    - .*
  prompt:
    - .*
  resource:
    - .*

dba:
  tool:
    - ^dba_*
    - ^base_*
    - ^sec_*
  prompt:
    - ^dba_*

dataScientist:
  tool:
    - ^base_*
    - ^rag_*
    - ^sql_*
    - ^fs_*
    - ^qlty_*
    - ^teradata_vectorstore_*
    - ^sec_userDbPermissions
    - ^dba_userSqlList
  prompt:
    - ^rag_*
    - ^sql_*
    - ^teradata_vectorstore_*

eda:
  tool:
    - "base_(?!(writeQuery|dynamicQuery)$).*"
    - qlty_.*
    - sec_userDbPermissions