# Teradata MCP Server Testing Framework Configuration

# Test execution settings
timeout_seconds: 300
max_retries: 1
parallel_execution: false
stop_on_first_failure: false

# Test filtering
test_patterns:
  - "test_*Tools"
module_patterns:
  - "*"
excluded_tests: []
excluded_modules: []

# Output settings
output_directory: "scripts/test_results"
generate_html_report: true
generate_json_report: true
verbose_logging: false

# Database settings
use_test_database: true
test_database_suffix: "_test"
cleanup_test_data: true

# LLM client settings
llm_provider: "anthropic"  # anthropic, openai
llm_model: "claude-3-sonnet-20240229"
llm_max_tokens: 4000
llm_temperature: 0.1

# Advanced settings
capture_tool_calls: true
save_conversation_logs: true
metadata: {}